from __future__ import annotations

from datetime import datetime
from typing import Dict, List, Mapping


def write_vcd(
    trace_by_names: Mapping[str, List[int]],
    filename: str,
    timescale: str = "1ns",
    top_module: str = "top",
    time_step: int = 1,
) -> None:
    """
    Convert a trace (per-cycle integer values) into a VCD file.

    Parameters
    ----------
    trace_by_names:
        Mapping from signal/expression name (str) to a list of integer values,
        one per time step. All lists must have the same length (the number of
        captured cycles).

    filename:
        Path to the output .vcd file.

    timescale:
        VCD timescale string, e.g. "1ns", "10ps", etc.

    top_module:
        Name used in the `$scope module <name> $end` line.

    time_step:
        Time step in VCD time units between consecutive entries
        in `trace_by_names`. For example:
          - timescale="1ns", time_step=10 → each cycle = 10 ns.
          - timescale="1ns", time_step=1  → each cycle = 1 ns.
    """
    if not trace_by_names:
        raise ValueError("trace_by_names is empty")

    lengths = {len(v) for v in trace_by_names.values()}
    if not lengths:
        raise ValueError("trace_by_names is empty")
    if len(lengths) > 1:
        raise ValueError("All traces must have the same length")

    num_steps = lengths.pop()
    if num_steps == 0:
        raise ValueError("trace_by_names contains no samples")

    # Compute bit-width for each signal from the maximum value seen
    max_values: Dict[str, int] = {name: 0 for name in trace_by_names}
    for name, values in trace_by_names.items():
        for value in values:
            if value < 0:
                raise ValueError(
                    f"Negative value {value} for signal '{name}'. "
                    "Convert to unsigned / two's-complement bits first."
                )
            if value > max_values[name]:
                max_values[name] = value

    widths: Dict[str, int] = {
        name: max(1, max_values[name].bit_length()) for name in trace_by_names
    }

    # Generate VCD identifier codes (can be any printable non-whitespace)
    # Here we just use s0, s1, s2, ...
    signal_names = sorted(trace_by_names)
    id_codes: Dict[str, str] = {
        name: f"s{idx}" for idx, name in enumerate(signal_names)
    }

    def _safe_name(name: str) -> str:
        # Avoid whitespace in VCD names
        return "".join("_" if c.isspace() else c for c in name)

    with open(filename, "w") as f:
        # Header
        f.write("$date\n")
        f.write(f"    {datetime.now()}\n")
        f.write("$end\n")
        f.write("$version\n")
        f.write("    Generated by write_vcd\n")
        f.write("$end\n")
        f.write(f"$timescale {timescale} $end\n")

        # Scope and variable declarations
        f.write(f"$scope module {top_module} $end\n")
        for name in signal_names:
            width = widths[name]
            code = id_codes[name]
            safe_name = _safe_name(name)
            f.write(f"$var wire {width} {code} {safe_name} $end\n")
        f.write("$upscope $end\n")
        f.write("$enddefinitions $end\n")

        # Initial values (#0, $dumpvars)
        current_values: Dict[str, int] = {}

        f.write("#0\n")
        f.write("$dumpvars\n")
        for name in signal_names:
            # All traces are assumed to have at least one sample (validated above)
            value = trace_by_names[name][0]
            current_values[name] = value
            width = widths[name]
            code = id_codes[name]

            if width == 1:
                bit = "1" if value else "0"
                f.write(f"{bit}{code}\n")
            else:
                mask = (1 << width) - 1
                bin_str = format(value & mask, f"0{width}b")
                f.write(f"b{bin_str} {code}\n")
        f.write("$end\n")

        # Subsequent time steps
        for step_idx in range(1, num_steps):
            vcd_time = step_idx * time_step
            changes: List[str] = []

            for name in signal_names:
                value = trace_by_names[name][step_idx]
                prev = current_values.get(name, None)
                if prev == value:
                    continue  # no change to dump

                current_values[name] = value
                width = widths[name]
                code = id_codes[name]

                if width == 1:
                    bit = "1" if value else "0"
                    changes.append(f"{bit}{code}\n")
                else:
                    mask = (1 << width) - 1
                    bin_str = format(value & mask, f"0{width}b")
                    changes.append(f"b{bin_str} {code}\n")

            if not changes:
                # No changes in this step → skip this time point for brevity
                continue

            f.write(f"#{vcd_time}\n")
            for line in changes:
                f.write(line)
