from __future__ import annotations

from datetime import datetime
from typing import Dict, List, Mapping, Iterable


def write_vcd(
    trace_history: List[Mapping[int, int]],
    trace_names: Mapping[int, str],
    filename: str,
    timescale: str = "1ns",
    top_module: str = "top",
    time_step: int = 1,
) -> None:
    """
    Convert a trace (per-cycle integer values) into a VCD file.

    Parameters
    ----------
    trace_history:
        List of time steps. Each element is a dict:
            { signal_id (int) -> value (int) }
        The list index is the time step (0, 1, 2, ...).
        Missing signal_ids in a step are treated as "no change".

    trace_names:
        Mapping from signal_id (int) to signal name (str) to be used in VCD.

    filename:
        Path to the output .vcd file.

    timescale:
        VCD timescale string, e.g. "1ns", "10ps", etc.

    top_module:
        Name used in the `$scope module <name> $end` line.

    time_step:
        Time step in VCD time units between consecutive entries
        in `trace_history`. For example:
          - timescale="1ns", time_step=10 → each cycle = 10 ns.
          - timescale="1ns", time_step=1  → each cycle = 1 ns.
    """
    if not trace_history:
        raise ValueError("trace_history is empty")

    # Collect all signal IDs we ever see
    all_ids = set(trace_names.keys())
    for step in trace_history:
        all_ids.update(step.keys())

    if not all_ids:
        raise ValueError("No signals found in trace_history / trace_names")

    # Compute bit-width for each signal from the maximum value seen
    max_values: Dict[int, int] = {sid: 0 for sid in all_ids}
    for step in trace_history:
        for sid, value in step.items():
            if value < 0:
                raise ValueError(
                    f"Negative value {value} for signal {sid}. "
                    "Convert to unsigned / two's-complement bits first."
                )
            if value > max_values[sid]:
                max_values[sid] = value

    widths: Dict[int, int] = {
        sid: max(1, max_values[sid].bit_length()) for sid in all_ids
    }

    # Generate VCD identifier codes (can be any printable non-whitespace)
    # Here we just use s0, s1, s2, ...
    id_codes: Dict[int, str] = {
        sid: f"s{idx}" for idx, sid in enumerate(sorted(all_ids))
    }

    def _safe_name(name: str) -> str:
        # Avoid whitespace in VCD names
        return "".join("_" if c.isspace() else c for c in name)

    with open(filename, "w") as f:
        # Header
        f.write("$date\n")
        f.write(f"    {datetime.now()}\n")
        f.write("$end\n")
        f.write("$version\n")
        f.write("    Generated by write_vcd\n")
        f.write("$end\n")
        f.write(f"$timescale {timescale} $end\n")

        # Scope and variable declarations
        f.write(f"$scope module {top_module} $end\n")
        for sid in sorted(all_ids):
            name = _safe_name(trace_names.get(sid, f"sig_{sid}"))
            width = widths[sid]
            code = id_codes[sid]
            f.write(f"$var wire {width} {code} {name} $end\n")
        f.write("$upscope $end\n")
        f.write("$enddefinitions $end\n")

        # Initial values (#0, $dumpvars)
        current_values: Dict[int, int] = {}
        first_step = trace_history[0]

        f.write("#0\n")
        f.write("$dumpvars\n")
        for sid in sorted(all_ids):
            if sid not in first_step:
                # No initial value → remain 'x' until first assignment
                continue
            value = first_step[sid]
            current_values[sid] = value
            width = widths[sid]
            code = id_codes[sid]

            if width == 1:
                bit = "1" if value else "0"
                f.write(f"{bit}{code}\n")
            else:
                mask = (1 << width) - 1
                bin_str = format(value & mask, f"0{width}b")
                f.write(f"b{bin_str} {code}\n")
        f.write("$end\n")

        # Subsequent time steps
        for step_idx, step in enumerate(trace_history[1:], start=1):
            vcd_time = step_idx * time_step
            changes: List[str] = []

            for sid, value in step.items():
                prev = current_values.get(sid, None)
                if prev == value:
                    continue  # no change to dump

                current_values[sid] = value
                width = widths[sid]
                code = id_codes[sid]

                if width == 1:
                    bit = "1" if value else "0"
                    changes.append(f"{bit}{code}\n")
                else:
                    mask = (1 << width) - 1
                    bin_str = format(value & mask, f"0{width}b")
                    changes.append(f"b{bin_str} {code}\n")

            if not changes:
                # No changes in this step → skip this time point for brevity
                continue

            f.write(f"#{vcd_time}\n")
            for line in changes:
                f.write(line)
