# Define stages
stages:
  - test

# Test job
pytest:
  stage: test
  image: python:3.13
  cache:
    paths:
      - .pip-cache/
  before_script:
    - pip install --cache-dir=.pip-cache pytest
    - pip install --cache-dir=.pip-cache -e .
  script:
    - PYTHONPATH=$(pwd) pytest
  tags:
    - x86