
from sprouthdl.aggregate.aggregate_record import AggregateRecord
from sprouthdl.aggregate.aggregate_array import Array
from sprouthdl.sprouthdl import SInt, UInt, Wire, Signal


from sprouthdl.sprouthdl import (
    UInt,
    Wire,
    Signal,
    Expr,
    Const,
    reset_shared_cache,
    Slice,
    HDLType,
)
from sprouthdl.sprouthdl_module import Module
from sprouthdl.sprouthdl_simulator import Simulator


def test_aggregate_record_basic():
    class MyRecord(AggregateRecord):
        a: Signal = Wire(UInt(8))
        b: Signal = Wire(SInt(4))
        c: Array = Array([Wire(UInt(8)) for _ in range(4)])

    b0 = MyRecord()
    b1 = MyRecord()

    # b0.a and b1.a are distinct Wire instances with same typ
    assert b0.a is not b1.a
    assert b0.a.typ.width == 8

    # Type inference:
    b0 <<= b1  # inferred return type: MyRecord (via HDLAggregate.__ilshift__)


# -------------------------------------------------------------------
# Test records used below
# -------------------------------------------------------------------


class MyRecord(AggregateRecord):
    a: Signal = Wire(UInt(8))
    b: Signal = Wire(UInt(4))


class RecordWithArray(AggregateRecord):
    a: Signal = Wire(UInt(8))
    vec: Array = Array([Wire(UInt(2)) for _ in range(3)])  # 3×2 bits


# -------------------------------------------------------------------
# Tests
# -------------------------------------------------------------------


def test_aggregaterecord_templates_collected():
    reset_shared_cache()

    # Templates should be captured on the class
    tmpl = MyRecord._record_field_templates
    assert set(tmpl.keys()) == {"a", "b"}
    assert isinstance(tmpl["a"], Signal)
    assert tmpl["a"].kind == "wire"
    assert tmpl["a"].typ.width == 8
    assert isinstance(tmpl["b"], Signal)
    assert tmpl["b"].kind == "wire"
    assert tmpl["b"].typ.width == 4


def test_aggregaterecord_instance_clones_wires():
    reset_shared_cache()

    b0 = MyRecord()
    b1 = MyRecord()

    # Each instance must have its own wires
    assert isinstance(b0.a, Signal)
    assert isinstance(b0.b, Signal)
    assert isinstance(b1.a, Signal)
    assert isinstance(b1.b, Signal)

    assert b0.a is not b1.a
    assert b0.b is not b1.b

    # Types preserved
    assert b0.a.typ.width == 8
    assert b0.b.typ.width == 4
    assert b0.a.kind == "wire"
    assert b0.b.kind == "wire"


def test_aggregaterecord_override_field_in_ctor():
    reset_shared_cache()

    custom_a = Wire(UInt(8), name="custom_a")
    b = MyRecord(a=custom_a)

    # 'a' is overridden
    assert b.a is custom_a
    # 'b' is still auto-cloned
    assert isinstance(b.b, Signal)
    assert b.b is not MyRecord._record_field_templates["b"]


def test_aggregaterecord_unknown_override_raises():
    reset_shared_cache()

    try:
        _ = MyRecord(x=Wire(UInt(8)))
        assert False, "Expected AttributeError for unknown override"
    except AttributeError:
        pass


def test_aggregaterecord_to_bits_and_width():
    reset_shared_cache()

    b = MyRecord()
    bits = b.to_bits()

    # Width = 8 + 4 = 12
    assert bits.typ.width == 12
    assert b.width == 12

    # to_bits must be an Expr
    assert isinstance(bits, Expr)


def test_aggregaterecord_assign_from_bits_slices_correctly():
    reset_shared_cache()

    b = MyRecord()

    # Total width 12 bits, use a constant with that width
    val = 0xABC  # 0b1010_1011_1100 (just something nontrivial)
    bits = Const(val, HDLType(12, signed=False, is_bool=False))

    # Structural assignment via HDLAggregate API
    b.assign(bits)

    # a: first 8 bits (LSB side)
    # b: next 4 bits
    assert isinstance(b.a, Signal)
    assert isinstance(b.b, Signal)
    assert b.a._driver._auto_generated # autogenerated signal, look one level deeper
    assert isinstance(b.a._driver._driver, Slice)
    assert b.b._driver._auto_generated # autogenerated signal, look one level deeper
    assert isinstance(b.b._driver._driver, Slice)

    # a gets bits[0:8]
    assert b.a._driver._driver.lsb == 0
    assert b.a._driver._driver.msb == 7

    # b gets bits[8:12]
    assert b.b._driver._driver.lsb == 8
    assert b.b._driver._driver.msb == 11


def test_aggregaterecord_elementwise_assign_from_other_record():
    reset_shared_cache()

    src = MyRecord()
    dst = MyRecord()

    # For clarity, drive src.a/src.b with constants
    src.a <<= Const(0x12, UInt(8))
    src.b <<= Const(0x3, UInt(4))

    # Element-wise assignment (<<=) uses field-wise semantics
    dst @= src

    assert isinstance(dst.a._driver, Signal)
    assert isinstance(dst.b._driver, Signal)

    # dst.a driven by src.a; dst.b driven by src.b
    assert dst.a._driver is src.a
    assert dst.b._driver is src.b


def test_aggregaterecord_with_nested_array_clone_and_width():
    reset_shared_cache()

    b0 = RecordWithArray()
    b1 = RecordWithArray()

    # a: 8 bits, vec: 3×2 bits → total width = 8 + 6 = 14
    assert b0.width == 14
    assert b1.width == 14

    # vec must be an Array, and elements must be distinct wires per instance
    assert isinstance(b0.vec, Array)
    assert isinstance(b1.vec, Array)

    assert len(b0.vec) == 3
    assert len(b1.vec) == 3

    for e0, e1 in zip(b0.vec, b1.vec):
        assert isinstance(e0, Signal)
        assert isinstance(e1, Signal)
        assert e0 is not e1
        assert e0.kind == "wire"
        assert e0.typ.width == 2

    bits0 = b0.to_bits()
    bits1 = b1.to_bits()
    assert bits0.typ.width == 14
    assert bits1.typ.width == 14


def test_aggregaterecord_with_nested_array_assign_from_bits():
    reset_shared_cache()

    b = RecordWithArray()

    # 8 + 3×2 = 14 bits
    val = 0x2A3F  # any value; lower 14 bits used
    bits = Const(val, HDLType(14, signed=False, is_bool=False))

    # Packed structural assignment into the record
    b.assign(bits)

    # a is 8 bits → should get the lowest 8 bits of val
    expected_a = val & ((1 << 8) - 1)
    assert _eval_expr(b.a) == expected_a

    # vec elements each 2 bits, in order:
    #   v0: bits[9:8], v1: bits[11:10], v2: bits[13:12]
    for idx, elem in enumerate(b.vec):
        expected_elem = (val >> (8 + 2 * idx)) & 0b11
        assert _eval_expr(elem) == expected_elem
        
# Small helper: evaluate an Expr to an integer using the simulator
def _eval_expr(e: Expr) -> int:
    m = Module("FPTest", with_clock=False, with_reset=False)
    sim = Simulator(m)
    return sim.peek(e)


if __name__ == "__main__":
    test_aggregate_record_basic()
    test_aggregaterecord_templates_collected()
    test_aggregaterecord_instance_clones_wires()
    test_aggregaterecord_override_field_in_ctor()
    test_aggregaterecord_unknown_override_raises()
    test_aggregaterecord_to_bits_and_width()
    test_aggregaterecord_assign_from_bits_slices_correctly()
    test_aggregaterecord_elementwise_assign_from_other_record()
    test_aggregaterecord_with_nested_array_clone_and_width()
    test_aggregaterecord_with_nested_array_assign_from_bits()
